# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c1859083391a86f8518f5711d3449bba168441c4c2f1627edffc3491c1fbec9fe1a6f4b8954e0f11a952558efd14034baeeeb7b9571c480c40a4547112b10a5

test:
  secret_key_base: e4cbb4c18069fd80d89104ac36db0c3e9fc983d77fdd65eb6067f0ecfe0a4532f64602233b042b716d85d4e94a7b89d87395b848265149844217e47e1438eb16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
